# Changes vs original scheduler:
# 1) All scheduler parameters are now persistent across reboots (restore_value).
# 2) Scheduler state is evaluated once after SNTP sync to apply immediately if inside the time window.
# 3) Temperature safety (safety_limit) has absolute priority and stops routing instantly.
# 4) UI remains identical to original (number/box, no sliders) to avoid ESP crashes.
substitutions:
  scheduler_unique_id: "Forced"
  custom_script: ${scheduler_unique_id}_fake_script

script:
  # Empty script if user does not define one
  - id: ${scheduler_unique_id}_fake_script
    then:

  # Central evaluation script (safe to call)
  - id: ${scheduler_unique_id}_evaluate
    mode: restart
    then:
      - lambda: |-
          // Do nothing until time is valid
          if (!id(${scheduler_unique_id}_sntp).now().is_valid()) {
            return;
          }

          // Safety has absolute priority
          if (id(safety_limit)) {
            id(router_level).publish_state(0);
            id(activate).turn_on();
            return;
          }

          int beginMin = (int) id(${scheduler_unique_id}_scheduler_begin_hour).state * 60
                       + (int) id(${scheduler_unique_id}_scheduler_begin_min).state;
          int endMin   = (int) id(${scheduler_unique_id}_scheduler_end_hour).state * 60
                       + (int) id(${scheduler_unique_id}_scheduler_end_min).state;
          int nowMin   = id(${scheduler_unique_id}_sntp).now().hour * 60
                       + id(${scheduler_unique_id}_sntp).now().minute;

          bool in_window;
          if (beginMin <= endMin) {
            in_window = (nowMin >= beginMin && nowMin < endMin);
          } else {
            in_window = (nowMin >= beginMin || nowMin < endMin);
          }

          if (id(${scheduler_unique_id}_scheduler_activate).state && in_window) {
            id(activate).turn_off();
            id(router_level).publish_state(
              id(${scheduler_unique_id}_scheduler_router_level).state
            );
          } else {
            id(router_level).publish_state(0);
            id(activate).turn_on();
          }

switch:
  - platform: template
    name: "Activate ${scheduler_unique_id} Scheduler"
    id: ${scheduler_unique_id}_scheduler_activate
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

number:
  - platform: template
    name: "${scheduler_unique_id} Scheduler Router Level"
    id: ${scheduler_unique_id}_scheduler_router_level
    min_value: 0
    max_value: 100
    step: 1
    mode: box
    optimistic: true
    restore_value: true
    initial_value: 100

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Hour"
    id: ${scheduler_unique_id}_scheduler_begin_hour
    min_value: 0
    max_value: 23
    step: 1
    mode: box
    optimistic: true
    restore_value: true
    initial_value: 0

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Minute"
    id: ${scheduler_unique_id}_scheduler_begin_min
    min_value: 0
    max_value: 55
    step: 5
    mode: box
    optimistic: true
    restore_value: true

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Hour"
    id: ${scheduler_unique_id}_scheduler_end_hour
    min_value: 0
    max_value: 23
    step: 1
    mode: box
    optimistic: true
    restore_value: true
    initial_value: 2

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Minute"
    id: ${scheduler_unique_id}_scheduler_end_min
    min_value: 0
    max_value: 55
    step: 5
    mode: box
    optimistic: true
    restore_value: true

time:
  - platform: sntp
    id: ${scheduler_unique_id}_sntp
    on_time:
      - seconds: 0
        minutes: /1
        then:
          - script.execute: ${scheduler_unique_id}_evaluate

esphome:
  on_boot:
    priority: -100
    then:
      - delay: 10s
      - script.execute: ${scheduler_unique_id}_evaluate
