# Differences vs original scheduler:
# 1) Stops the scheduler automatically if safety temperature is reached
# 2) Uses existing stop_temperature value (no hardcoded threshold)
# 3) Temperature is checked periodically during scheduler time window
# 4) Adds logs to debug temperature readings and decisions

substitutions:
  scheduler_unique_id: "Forced"
  custom_script: ${scheduler_unique_id}_fake_script

script:
  # Fake empty script if user does not provide one
  - id: ${scheduler_unique_id}_fake_script
    then:

  # Check temperature and stop scheduler if limit is reached
  - id: check_temperature_for_${scheduler_unique_id}_scheduler
    mode: single
    then:
      - lambda: |-
          ESP_LOGI(
            "scheduler_temp",
            "Temp check: %.2f °C (stop at %.2f °C)",
            id(safety_temperature).state,
            id(stop_temperature).state
          );

          if (!isnan(id(safety_temperature).state) &&
              id(safety_temperature).state >= id(stop_temperature).state) {
            ESP_LOGW(
              "scheduler_temp",
              "Temperature limit reached → stopping scheduler"
            );
            id(${scheduler_unique_id}_scheduler_activate).turn_off();
          }

switch:
  # Scheduler enable/disable
  - platform: template
    name: "Activate ${scheduler_unique_id} Scheduler"
    id: "${scheduler_unique_id}_scheduler_activate"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_off:
      then:
        - if:
            condition:
              - switch.is_off: activate
            then:
              - number.set:
                  id: router_level
                  value: 0
              - switch.turn_on: activate

number:
  - platform: template
    name: "${scheduler_unique_id} Scheduler Router Level"
    id: "${scheduler_unique_id}_scheduler_router_level"
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: "%"
    optimistic: true
    mode: slider
    restore_value: true
    initial_value: 100

  - platform: template
    name: "${scheduler_unique_id} Scheduler Checking End Threshold"
    id: "${scheduler_unique_id}_scheduler_checking_end_threshold"
    min_value: 0
    max_value: 720
    step: 5
    mode: box
    optimistic: true
    restore_value: true
    initial_value: 5

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Minute"
    id: "${scheduler_unique_id}_scheduler_begin_min"
    min_value: 0
    max_value: 55
    step: 5
    mode: box
    optimistic: true
    restore_value: true
    initial_value: 0

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Minute"
    id: "${scheduler_unique_id}_scheduler_end_min"
    min_value: 0
    max_value: 55
    step: 5
    mode: box
    optimistic: true
    restore_value: true
    initial_value: 0

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Hour"
    id: "${scheduler_unique_id}_scheduler_begin_hour"
    min_value: 0
    max_value: 23
    step: 1
    mode: box
    optimistic: true
    restore_value: true
    initial_value: 22

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Hour"
    id: "${scheduler_unique_id}_scheduler_end_hour"
    min_value: 0
    max_value: 23
    step: 1
    mode: box
    optimistic: true
    restore_value: true
    initial_value: 6

time:
  - platform: sntp
    id: ${scheduler_unique_id}_sntp
    on_time:
      - seconds: 0
        minutes: /5
        then:
          - if:
              condition:
                - switch.is_on: ${scheduler_unique_id}_scheduler_activate
              then:
                - if:
                    condition:
                      lambda: |-
                        int beginTotal =
                          id(${scheduler_unique_id}_scheduler_begin_hour).state * 60 +
                          id(${scheduler_unique_id}_scheduler_begin_min).state;

                        int endTotal =
                          id(${scheduler_unique_id}_scheduler_end_hour).state * 60 +
                          id(${scheduler_unique_id}_scheduler_end_min).state;

                        int nowTotal =
                          id(${scheduler_unique_id}_sntp).now().hour * 60 +
                          id(${scheduler_unique_id}_sntp).now().minute;

                        if (beginTotal <= endTotal) {
                          return nowTotal >= beginTotal && nowTotal < endTotal;
                        } else {
                          return nowTotal >= beginTotal || nowTotal < endTotal;
                        }
                    then:
                      # Scheduler active → force router level
                      - switch.turn_off: activate
                      - number.set:
                          id: router_level
                          value: !lambda return id(${scheduler_unique_id}_scheduler_router_level).state;

                      # Temperature safety check
                      - script.execute: check_temperature_for_${scheduler_unique_id}_scheduler

                      # Optional custom script
                      - script.execute: ${custom_script}

                    else:
                      - if:
                          condition:
                            and:
                              - switch.is_off: activate
                              - lambda: |-
                                  int endTotal =
                                    id(${scheduler_unique_id}_scheduler_end_hour).state * 60 +
                                    id(${scheduler_unique_id}_scheduler_end_min).state;

                                  int nowTotal =
                                    id(${scheduler_unique_id}_sntp).now().hour * 60 +
                                    id(${scheduler_unique_id}_sntp).now().minute;

                                  return nowTotal >= endTotal &&
                                         nowTotal <= endTotal +
                                         id(${scheduler_unique_id}_scheduler_checking_end_threshold).state;
                          then:
                            - number.set:
                                id: router_level
                                value: 0
                            - switch.turn_on: activate
