# Forced Scheduler with Temperature Guard and Daily Temperature Memory
# - Stops scheduler when stop_temperature is reached or safety_limit is active
# - Remembers if temperature was reached during the day (08h–19h)
# - Prevents night forced heating if water was already hot
# - Fully autonomous and reboot-safe

substitutions:
  scheduler_unique_id: "Forced"
  custom_script: ${scheduler_unique_id}_fake_script

globals:
  # Remember if temperature was reached during the day
  - id: temperature_atteinte_journee
    type: bool
    restore_value: true
    initial_value: "false"

script:
  # Fake script (unchanged)
  - id: ${scheduler_unique_id}_fake_script
    then:

  # === DAILY TEMPERATURE MEMORY UPDATE ===
  - id: ${scheduler_unique_id}_day_temperature_tracker
    mode: single
    then:
      - lambda: |-
          auto now = id(${scheduler_unique_id}_sntp).now();
          if (!now.is_valid()) return;

          int minutes = now.hour * 60 + now.minute;
          bool is_day = (minutes >= 8 * 60) && (minutes < 19 * 60);

          if (!is_day) return;

          if (
            !isnan(id(safety_temperature).state) &&
            id(safety_temperature).state >= id(stop_temperature).state
          ) {
            if (!id(temperature_atteinte_journee)) {
              ESP_LOGI("forced_scheduler", "Day temperature reached -> memorized");
            }
            id(temperature_atteinte_journee) = true;
          }

  # === TEMPERATURE / SAFETY GUARD ===
  - id: ${scheduler_unique_id}_temperature_guard
    mode: single
    then:
      - lambda: |-
          auto now = id(${scheduler_unique_id}_sntp).now();
          if (!now.is_valid()) return;

          int now_min = now.hour * 60 + now.minute;
          int begin_min =
            id(${scheduler_unique_id}_scheduler_begin_hour).state * 60 +
            id(${scheduler_unique_id}_scheduler_begin_min).state;
          int end_min =
            id(${scheduler_unique_id}_scheduler_end_hour).state * 60 +
            id(${scheduler_unique_id}_scheduler_end_min).state;

          bool in_scheduler_window;
          if (begin_min <= end_min) {
            in_scheduler_window = (now_min >= begin_min && now_min < end_min);
          } else {
            in_scheduler_window = (now_min >= begin_min || now_min < end_min);
          }

          if (!in_scheduler_window) return;

          bool temp_reached =
            !isnan(id(safety_temperature).state) &&
            id(safety_temperature).state >= id(stop_temperature).state;

          if (id(safety_limit) || temp_reached) {
            ESP_LOGW("forced_scheduler",
              "Stopping Forced Scheduler (temp=%.1f / safety=%d)",
              id(safety_temperature).state,
              id(safety_limit)
            );
            id(${scheduler_unique_id}_scheduler_activate).turn_off();
          }

switch:
  - platform: template
    name: "Activate ${scheduler_unique_id} Scheduler"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    id: "${scheduler_unique_id}_scheduler_activate"
    on_turn_off:
      then:
        - if:
            condition:
              - switch.is_off: activate
            then:
              - number.set:
                  id: router_level
                  value: 0
              - switch.turn_on: activate

  # Visible in Home Assistant
  - platform: template
    name: "Temp atteinte aujourd'hui"
    id: temperature_atteinte_journee_switch
    optimistic: true
    lambda: |-
      return id(temperature_atteinte_journee);
    turn_on_action:
      - lambda: |-
          id(temperature_atteinte_journee) = true;
    turn_off_action:
      - lambda: |-
          id(temperature_atteinte_journee) = false;

number:
  - platform: template
    name: "${scheduler_unique_id} Scheduler Router Level"
    id: "${scheduler_unique_id}_scheduler_router_level"
    min_value: 0
    max_value: 100
    initial_value: 100
    step: 1
    unit_of_measurement: "%"
    optimistic: true
    mode: slider

  - platform: template
    name: "${scheduler_unique_id} Scheduler Checking End Threshold"
    id: "${scheduler_unique_id}_scheduler_checking_end_threshold"
    min_value: 0
    max_value: 720
    step: 5
    initial_value: 5
    optimistic: true

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Minute"
    id: "${scheduler_unique_id}_scheduler_begin_min"
    min_value: 0
    max_value: 55
    step: 5
    initial_value: 0
    optimistic: true

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Minute"
    id: "${scheduler_unique_id}_scheduler_end_min"
    min_value: 0
    max_value: 55
    step: 5
    initial_value: 0
    optimistic: true

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Hour"
    id: "${scheduler_unique_id}_scheduler_begin_hour"
    min_value: 0
    max_value: 23
    step: 1
    initial_value: 22
    optimistic: true

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Hour"
    id: "${scheduler_unique_id}_scheduler_end_hour"
    min_value: 0
    max_value: 23
    step: 1
    initial_value: 6
    optimistic: true

time:
  - platform: sntp
    id: ${scheduler_unique_id}_sntp
    on_time:
      # Reset daily memory at 08:00
      - seconds: 0
        minutes: 0
        hours: 8
        then:
          - lambda: |-
              ESP_LOGI("forced_scheduler", "Daily temperature memory reset");
              id(temperature_atteinte_journee) = false;

      # Every minute: update memory + safety guard
      - seconds: 0
        minutes: /1
        then:
          - script.execute: ${scheduler_unique_id}_day_temperature_tracker
          - script.execute: ${scheduler_unique_id}_temperature_guard
