# Stop Forced Scheduler when temperature is above stop_temperature
# or when Safety limit reached is active
# Track if temperature was reached during the day (08h–19h)
# Variable is persistent and reset every day at 08:00
# Forced Scheduler decision is evaluated at BOOT and at 19:00

substitutions:
  scheduler_unique_id: "Forced"
  custom_script: ${scheduler_unique_id}_fake_script

script:
  # Fake empty script (compatibility)
  - id: ${scheduler_unique_id}_fake_script
    then:

  # === DAY TEMPERATURE TRACKING (08h–19h) ===
  - id: ${scheduler_unique_id}_day_temperature_tracker
    mode: single
    then:
      - lambda: |-
          auto now = id(${scheduler_unique_id}_sntp).now();
          if (!now.is_valid()) return;

          int now_min = now.hour * 60 + now.minute;
          if (now_min < 8 * 60 || now_min >= 19 * 60) return;

          if (
            !isnan(id(safety_temperature).state) &&
            id(safety_temperature).state >= id(stop_temperature).state
          ) {
            if (!id(temperature_atteinte_60).state) {
              ESP_LOGI("forced_scheduler",
                "Temperature reached during the day → disable forced tonight");
              id(temperature_atteinte_60).turn_on();
            }
          }

  # === SAFETY GUARD DURING FORCED WINDOW ===
  - id: ${scheduler_unique_id}_temperature_guard
    mode: single
    then:
      - lambda: |-
          auto now = id(${scheduler_unique_id}_sntp).now();
          if (!now.is_valid()) return;

          int now_min = now.hour * 60 + now.minute;
          int begin_min =
            id(${scheduler_unique_id}_scheduler_begin_hour).state * 60 +
            id(${scheduler_unique_id}_scheduler_begin_min).state;
          int end_min =
            id(${scheduler_unique_id}_scheduler_end_hour).state * 60 +
            id(${scheduler_unique_id}_scheduler_end_min).state;

          bool in_window;
          if (begin_min <= end_min)
            in_window = (now_min >= begin_min && now_min < end_min);
          else
            in_window = (now_min >= begin_min || now_min < end_min);

          if (!in_window) return;

          bool temp_reached =
            !isnan(id(safety_temperature).state) &&
            id(safety_temperature).state >= id(stop_temperature).state;

          if (id(safety_limit) || temp_reached) {
            ESP_LOGW("forced_scheduler",
              "STOP forced scheduler (temp=%.1f safety=%d)",
              id(safety_temperature).state,
              id(safety_limit)
            );
            id(${scheduler_unique_id}_scheduler_activate).turn_off();
          }

  # === DECIDE IF FORCED SCHEDULER SHOULD RUN ===
  # Executed at BOOT and at 19:00
  - id: ${scheduler_unique_id}_forced_decision
    mode: single
    then:
      - lambda: |-
          auto now = id(${scheduler_unique_id}_sntp).now();
          if (!now.is_valid()) return;

          bool temp_ok =
            !isnan(id(safety_temperature).state) &&
            id(safety_temperature).state < id(stop_temperature).state;

          if (
            !id(safety_limit) &&
            temp_ok &&
            !id(temperature_atteinte_60).state
          ) {
            ESP_LOGI("forced_scheduler", "Forced Scheduler ENABLED");
            id(${scheduler_unique_id}_scheduler_activate).turn_on();
          } else {
            ESP_LOGI("forced_scheduler", "Forced Scheduler DISABLED");
            id(${scheduler_unique_id}_scheduler_activate).turn_off();
          }

switch:
  # Persistent day flag
  - platform: template
    name: "Temp atteinte dans la journée"
    id: temperature_atteinte_60
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

  # Forced Scheduler main switch
  - platform: template
    name: "Activate ${scheduler_unique_id} Scheduler"
    id: "${scheduler_unique_id}_scheduler_activate"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_off:
      then:
        - if:
            condition:
              - switch.is_off: activate
            then:
              - number.set:
                  id: router_level
                  value: 0
              - switch.turn_on: activate

number:
  - platform: template
    name: "${scheduler_unique_id} Scheduler Router Level"
    id: "${scheduler_unique_id}_scheduler_router_level"
    min_value: 0
    max_value: 100
    initial_value: 100
    step: 1
    unit_of_measurement: "%"
    optimistic: true
    mode: slider

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Hour"
    id: "${scheduler_unique_id}_scheduler_begin_hour"
    min_value: 0
    max_value: 23
    step: 1
    optimistic: true
    mode: box
    initial_value: 22

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Hour"
    id: "${scheduler_unique_id}_scheduler_end_hour"
    min_value: 0
    max_value: 23
    step: 1
    optimistic: true
    mode: box
    initial_value: 6

time:
  - platform: sntp
    id: ${scheduler_unique_id}_sntp

    on_time:
      # Reset daily flag at 08:00
      - hours: 8
        minutes: 0
        seconds: 0
        then:
          - switch.turn_off: temperature_atteinte_60

      # Decision at 19:00
      - hours: 19
        minutes: 0
        seconds: 0
        then:
          - script.execute: ${scheduler_unique_id}_forced_decision

      # Every minute checks
      - seconds: 0
        minutes: /1
        then:
          - script.execute: ${scheduler_unique_id}_day_temperature_tracker
          - script.execute: ${scheduler_unique_id}_temperature_guard

esphome:
  on_boot:
    priority: -100
    then:
      - script.execute: ${scheduler_unique_id}_forced_decision
